Added Test Formulas and Test formulas tutorial
ZupIT/ritchie-docs pull request #149
Opened 2021-08-19 19:39 UTC by jessica-tw

- Added 'Test formula' to Formulas section; 
- Added new tutorial 'How to test formulas outputs' 
- Created a Contribute section to be moved to the menu.

2021-08-19 21:03 UTC, GuillaumeFalourd requested changes

2021-08-19 21:03 UTC, GuillaumeFalourd commented on content/pt-br/Fórmulas/testar formulas.md
> +No contexto do Ritchie CLI, Unit tests é a forma de testar uma parte da implementação da sua fórmula.
Podemos traduzir `Unit tests` para `testes unitários`

2021-08-19 21:03 UTC, GuillaumeFalourd commented on content/pt-br/Fórmulas/testar formulas.md
> +Alguns templates de fórmula, como Java e Golang possuem classe de testes para escrever e rodar testes unit das fórmulas.
Substituir `unit` por `unitário`

2021-08-20 12:18 UTC, jessica-tw commented on content/pt-br/Fórmulas/testar formulas.md
> +No contexto do Ritchie CLI, Unit tests é a forma de testar uma parte da implementação da sua fórmula.
done! ;)

2021-08-20 16:17 UTC, GuillaumeFalourd approved these changes
👍🏼

2021-08-20 16:17 UTC, merged