fixed readme
ZupIT/ritchie-docs pull request #162
Opened 2021-11-08 20:41 UTC by jessica-tw

Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>

- Updated README.

2021-11-08 21:12 UTC, mdcpmoreira reviewed
TW review done ;)

2021-11-08 21:12 UTC, mdcpmoreira commented on README.md
>  ### All your automations in one place
I think that we don't need to maintain this introduction, considering we want to establish the same pattern for all docs repositories. I'd just delete these phrase and go straight forward "Ritchie CLI is an open source..."

2021-11-08 21:12 UTC, mdcpmoreira commented on README.md
>  **Ritchie CLI** is an open source project that allows to **create**, **store** and **share** automations, executing them through command lines.
```suggestion
**Ritchie CLI** is an open source project that allows to create, store and share automations, executing them through command lines.
```

2021-11-08 21:12 UTC, mdcpmoreira commented on README.md
>  Once you've cloned this repo, from the `root` folder, run:
```suggestion
Once you've cloned this repo, from the `root` folder, run the command:
```

2021-11-08 21:12 UTC, mdcpmoreira commented on README.md
>  You can suggest a change, a fix, or improvements to our documentation, for example:
```suggestion
You can suggest a change, a fix, or improvements to our documentation, such as: 
```

2021-11-09 20:50 UTC, lucasdittrichzup requested changes

2021-11-09 20:50 UTC, lucasdittrichzup commented on CONTRIBUTING.md
> +Is this the first CharlesCD repository you visit? Check out other [**repositories**](https://github.com/ZupIT/ritchie-cli).
Ritchie CLI

2021-11-09 20:50 UTC, lucasdittrichzup commented on README.md
> +This repository uses [**hugo server**](https://gohugo.io/commands/hugo_server/) and contains [**Ritchie CLI**](https://ritchiecli.io/) official documentation.
the correct link for the doc is: https://docs.ritchiecli.io/

2021-11-09 20:50 UTC, lucasdittrichzup commented on CONTRIBUTING.md
> +Check out the requisites before contributing to CharlesCD documentation:
Ritchie CLI

2021-11-10 13:34 UTC, lucasdittrichzup approved these changes

2021-11-12 19:44 UTC, GuillaumeFalourd approved these changes
👍🏼

2021-11-12 19:53 UTC, merged